In [65]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [66]:
import pandas as pd

In [67]:
df = pd.read_csv('/content/drive/MyDrive/LR-by-codebasics/hiring.csv')

In [68]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [69]:
df.shape

(8, 4)

In [70]:
# checking for NaN values across the data
df.isnull().sum()

experience                    2
test_score(out of 10)         1
interview_score(out of 10)    0
salary($)                     0
dtype: int64

In [71]:
# Col-wise NaN values in %
df.isnull().mean()*100

experience                    25.0
test_score(out of 10)         12.5
interview_score(out of 10)     0.0
salary($)                      0.0
dtype: float64

In [72]:
pip install word2number

In [73]:
from word2number import w2n

In [74]:
w2n.word_to_num('ninety eight')

98

In [75]:
df.columns

Index(['experience', 'test_score(out of 10)', 'interview_score(out of 10)',
       'salary($)'],
      dtype='object')

In [76]:
df['experience'] = df['experience'].apply(lambda x: w2n.word_to_num(x) if isinstance(x, str) else x)

In [77]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         NaN                    8.0                           9      50000
1         NaN                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    NaN                           7      72000
7        11.0                    7.0                           8      80000

In [78]:
df['experience'].median()

6.0

In [79]:
df['experience'] = df['experience'].fillna(df['experience'].median())

In [80]:
df['test_score(out of 10)'].median()

8.0

In [81]:
df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(df['test_score(out of 10)'].median())

In [85]:
df.isnull().sum()

experience                    0
test_score(out of 10)         0
interview_score(out of 10)    0
salary($)                     0
dtype: int64

In [86]:
X, y = df.drop('salary($)', axis=1), df['salary($)']

In [87]:
X

experience  test_score(out of 10)  interview_score(out of 10)
0         6.0                    8.0                           9
1         6.0                    8.0                           6
2         5.0                    6.0                           7
3         2.0                   10.0                          10
4         7.0                    9.0                           6
5         3.0                    7.0                          10
6        10.0                    8.0                           7
7        11.0                    7.0                           8

In [88]:
y

0    50000
1    45000
2    60000
3    65000
4    70000
5    62000
6    72000
7    80000
Name: salary($), dtype: int64

Model - LR

In [89]:
from sklearn.linear_model import LinearRegression

In [90]:
lr = LinearRegression()

In [91]:
lr.fit(X, y)

LinearRegression()

In [92]:
# [w1, w2, w3]
lr.coef_

array([2813.00813008, 1333.33333333, 2926.82926829])

In [93]:
# w0
lr.intercept_

np.float64(11869.91869918695)

In [94]:
# y = w0 + w1*x1 + w2*x2 + w3*x3
# salary = w0 + w1*experience + w2*test_score + w3*interview_score

''' Predict Salaries of candidates who has
1. 2 yr experience, 9 test score, 6 interview score
2. 12 yr experience, 10 test score, 10 interview score
'''

In [95]:
lr.predict([[2, 9, 6]])

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([47056.91056911])

In [96]:
lr.predict([[12, 10, 10]])

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([88227.64227642])