In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/LR-by-codebasics/homeprices.csv')

In [ ]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [ ]:
df.shape

(6, 4)

In [ ]:
# checking for NaN values across the data
df.isnull().sum()

area        0
bedrooms    1
age         0
price       0
dtype: int64

In [ ]:
# Col wise NaN values in %
df.isnull().mean()*100

area         0.000000
bedrooms    16.666667
age          0.000000
price        0.000000
dtype: float64

In [ ]:
df['bedrooms'].mean()

np.float64(4.2)

In [ ]:
df['age'].mean()

np.float64(16.5)

In [ ]:
df['bedrooms'].median()

4.0

In [ ]:
import math

In [ ]:

df['bedrooms'] = df['bedrooms'].fillna(math.floor(df['bedrooms'].median()))

In [ ]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [ ]:
df.columns

Index(['area', 'bedrooms', 'age', 'price'], dtype='object')

In [ ]:
X,y = df[['area', 'bedrooms', 'age']], df['price']
print(X.shape)
print(y.shape)

(6, 3)
(6,)


In [ ]:
X.head(3)

area  bedrooms  age
0  2600       3.0   20
1  3000       4.0   15
2  3200       4.0   18

In [ ]:
y.head(3)

0    550000
1    565000
2    610000
Name: price, dtype: int64

Model - LR

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
lr = LinearRegression()

In [ ]:
lr.fit(X, y)

LinearRegression()

In [ ]:
# [w1, w2, w3]
lr.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [ ]:
# w0
lr.intercept_

np.float64(221323.00186540396)

In [ ]:
# y = w0 + w1*x1 + w2*x2 + w3*x3
# price = w0 + w1*area + w2*bedrooms + w3*age

''' find out price of a home that has
1. 3000 sqr ft area, 3 bedrooms, 40 year old
2. 2500 sqr ft area, 4 bedrooms, 5 year old
'''

1. Home has
3000 sqr ft area, 3 bedrooms, 40 year old

In [ ]:
lr.predict([[3000, 3, 40]])

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [ ]:
112.06244194*3000 + 23388.88007794*3 + -3231.71790863*40 + 221323.00186540396

498408.251574024

2. Home has 2500 sqr ft area, 4 bedrooms, 5 year old

In [ ]:
lr.predict([[2500, 4, 5]])

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([578876.03748933])

In [ ]:
112.06244194*2500 + 23388.88007794*4 + -3231.71790863*5 + 221323.00186540396

578876.0374840139